namespace: dellemc_networking
name: os10
version: 0.1.0
readme: README.md
authors:
 - Abirami N (github.com/abirami-n)
description: null
license: GPL-3.0-or-later
license_file: COPYING
tags: null
dependencies:
  ansible.netcommon: '>=0.0.1'
repository: https://github.com:ansible-collections/dellemc_networking.os10.git
documentation: https://github.com/ansible-collections/dellemc_networking.os10/tree/master/docs
homepage: https://github.com:ansible-collections/dellemc_networking.os10
issues: https://github.com:ansible-collections/dellemc_networking.os10
