name: CI
on:
- pull_request

jobs:
  sanity:
    name: Sanity (${{ matrix.ansible }})
    strategy:
      matrix:
        ansible:
        - stable-2.12
        - stable-2.13
        - stable-2.14
        - stable-2.15
    runs-on: ubuntu-latest
    steps:

      - name: Check out code
        uses: actions/checkout@v1
        with:
          path: ansible_collections/dellemc/os10

      - name: Set up Python "3.10"
        uses: actions/setup-python@v1
        with:
          python-version: "3.10"

      - name: Install ansible-base (${{ matrix.ansible }})
        run: pip install https://github.com/ansible/ansible/archive/${{ matrix.ansible }}.tar.gz --disable-pip-version-check

      - name: Install ansible_collections.ansible.netcommon
        run: ansible-galaxy collection install ansible.netcommon -p ../../

      - name: Run sanity tests
        run: ansible-test sanity --docker -v --color --python "3.10"
